org: brianjenney
app: warehouse
service: warehouse
provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: us-east-1
    memorySize: 128
    useDotEnv: true
functions:
    app:
        handler: dist/server.handler
        events:
            - http:
                  path: /
                  method: ANY
                  cors: true
            - http:
                  path: /{proxy+}
                  method: ANY
                  cors: true
